### ISSUE TITLE
Can't find the tourism dataset in GL3D's data

### ISSUE THREAD

**Issue by ze-n-g** [THU-LYJ-Lab/DarkFeat#3]
Thank you for your reply, I can't find the tourism dataset in GL3D's tourism_data.md, if it's convenient for you, please provide the link of the tourism dataset.

_Originally posted by @ze-n-g in https://github.com/THU-LYJ-Lab/DarkFeat/issues/2#issuecomment-1629943719_

**Comment by ze-n-g** [comment]
Thank you so much for your open source work, I'm trying to follow your work normally, I have two questions now
1. One is whether to share tourism data .
2. There are three steps in the training phase. How much is the loss stable after each step of training, and  how much time is required for each step?

**Comment by hyz317** [comment]
The links provided in GL3D's tourism_data.md file seem expired. As a result, I cannot provide you with the direct link to the dataset you're looking for. I recommend you reach out to the authors of GL3D directly.

Due to the high diversity of GL3D image pairs, which is specifically reflected in the loss curves, there are still fluctuations between samples after the overall trend of the loss becomes stable.
In our implementation, the three training phases were trained with 160k, 60k, and 50k iterations, taking about 3 days, 2 days, and 1.5 days, respectively.
